### ISSUE TITLE
Failed to find any WMC data (win10 WMP only)

### ISSUE THREAD

**Issue by BlinkzFox** [jojo2357/Music-Discord-Rich-Presence#85] opened 2023-05-02 22:11 UTC
![image](https://user-images.githubusercontent.com/99220871/235796861-3edf4d35-8504-4af2-a8aa-404a320730ed.png)
It detects and accepts wmplayer, but says this message over and over and fails to update discord status. It works fine with groove.

**Comment by jojo2357** [comment] 2023-05-02 22:17
I strongly suspect that this is a duplicate of #76. This is not under my control. WMP does not reliably report its media to WMC which baffles me. If WMP does not make any information available, then there is nothing MDRP can do, short of hacking.

**Closed** 2023-05-03 02:40 UTC
Labels: duplicate, wontfix, WMP is TRASH
