### ISSUE TITLE
MDRP pulling song details only when equalizer is active

### ISSUE THREAD

**Issue by xxFoxGuyxx** [jojo2357/Music-Discord-Rich-Presence#101] opened 2024-09-27 02:48 UTC
**Version**
Running on Windows 10
The version the bug was found on: 1.7.3

**Describe the bug**
Song details will only display when equalizer tab is active. 

**To Reproduce**
1. Run Groove Music Player and the MDRP
2. Play any song
3. Read MDRP output
4. No song details outputted
5. Open equalizer settings
6. MDRP output shows song detail

**Expected behavior**
Expected the song details to instantly appear as music started to play. Resulted in a blank output until the equalizer was opened.

**Screenshots**
![img4](https://github.com/user-attachments/assets/3dc25214-77f8-454c-9dfb-ef84c70e1b0b)
![img3](https://github.com/user-attachments/assets/2ebd50dd-3131-41f5-895d-e941bc51f2c9)

**Additional context**
n/a

**Comment by jojo2357** [comment] 2024-09-27 03:55
Duplicate of #76 

WMP (groove) sucks and doesnt play nice with WMC (made by Microsoft). There is nothing I can do.

**Closed as not planned by jojo2357** 2024-09-27 03:55 UTC
