### ISSUE TITLE
DRP only shows playing songs locally, not for other people

### ISSUE THREAD

**Issue by xDoomrush** [jojo2357/Music-Discord-Rich-Presence#74] opened 2022-09-08 11:15 UTC
I've been tweaking with this since I found it recently, and I've gotten it to play most of the unreleased music I frequently listen to however, I was able to get someone on discord to see it momentarily but it kept disappearing according to them, I've logged into an alt discord account and have attached pictures below.

Secondly, much less critical, it seems difficult to set album art for the unreleased music I spoke of obviously, it can't grab them automatically because the songs aren't released but trying to do it manually through the file didn't work for me either but this issue is less important than the main one.

![DRP local](https://user-images.githubusercontent.com/15260491/189108413-baa7c286-cb0f-41e1-b998-0f6894a37a19.png)
![DRP view from alt acc](https://user-images.githubusercontent.com/15260491/189108423-8739c46c-3bc2-49b2-a1b9-87a634d79bed.png)

**Comment by jojo2357** [comment] 2022-09-08 16:54
Which music player are you using, and does it fully appear in the console? I am hoping the issue resolves itself because I have no idea where to start debugging. 

Ad for the keying problem, you should refer to the tutorials linked in the readme. Make sure to jot down artist and album **exactly** as it appears in the console, save the dat file, and then restart mdrp. If the issue persists then commandeer a working dat file (maybe the cache) and add your own lines. If that still doesnt work then you can either join my discord for more help or maybe the issue is related to the other one

**Comment by xDoomrush** [comment] 2022-09-09 08:56
I'm using spotify, and ill provide a screenshot of the console, also I did follow the included video tutorial, as well as went through the read me, and tried troubleshooting but to no avail.

Note that I have previously gotten it to key properly( in the sense that it says "This is a good one, check DRP" but it still didn't show the image linked

![DRP console](https://user-images.githubusercontent.com/15260491/189312360-bd640953-2636-4581-aada-5c7c221c4709.png)

**Comment by xDoomrush** [comment] 2022-09-20 23:44
I've been unable to find a solution, have you got any ideas?

**Comment by jojo2357** [comment] 2022-09-21 00:18
Im sorry it seems that my previous comment was not sent. What I meant to ask was for you to send your key file because I am pretty sure that something has to be wrong there. 

As for the not showing up in discord thing, I can't and won't help with that because it is just so out of my control I dont have time to hunt an issue like that down on a system that isnt mine

**Comment by jojo2357** [comment] 2022-11-30 20:23
Closing as abandoned by the author

**Closed by jojo2357** 2022-11-30 20:23 UTC
Labels: question
